services:
  db-cron-task:
    container_name: db-cron-task
    hostname: postgres
    image: postgres:14
    restart: always
    env_file: .env
    expose  :
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - ./data:/var/lib/postgresql/data

  cron-task:
    image: cron-task
    container_name: cron-task
    depends_on:
      - db-cron-task
    build:
      context: .
    restart: unless-stopped
    volumes:
      - .:/app

volumes:
  postgres_data:
