version: "3.8"

services:
  db-cron-task:
    container_name: db-cron-task
    hostname: postgres
    image: postgres:14
    restart: always
    env_file: .env
    networks:
      - cron_net
    expose  :
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    command: postgres -c listen_addresses='*' -p $POSTGRES_PORT
    volumes:
      - ./data:/var/lib/postgresql/data

  cron-task:
    image: cron-task
    container_name: cron-task
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app

networks:
  cron_net:

volumes:
  postgres_data:
