name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Greetings! Thanks for your contribution. Please, feel free to contact the maintainer at brunolnetto@gmail.com"
        pr-message: "Thanks for pull request. This will be of great help on further usage."
